import Foundation

/// Bảng dịch. Khoá = chuỗi TIẾNG VIỆT gốc trong code.
///
/// `vi` không cần bảng (trả nguyên khoá). Ngôn ngữ chưa có bảng → lùi về `en`.
/// Bổ sung dần theo từng lô dịch. Thiếu khoá nào → tự hiển thị bằng tiếng Việt,
/// dễ thấy chỗ chưa dịch.
enum LocTables {
    static let all: [AppLanguage: [String: String]] = [
        .en: enTable
    ]
}

/// Lô 1 — vỏ app: menu trên cùng, màn hình Home, tab bên trái, thanh công cụ, Cài đặt.
private let enTable: [String: String] = [
    // MARK: Cài đặt / ngôn ngữ
    "Ngôn ngữ": "Language",
    "Đổi ngôn ngữ": "Change language",
    "Mở lại ngay": "Relaunch now",
    "Để sau": "Later",
    "Mở lại app để áp dụng ngôn ngữ mới.": "Relaunch the app to apply the new language.",
    "Tiếng Việt và English đã dịch đầy đủ. Các ngôn ngữ khác tạm hiển thị bằng English.":
        "Vietnamese and English are fully translated. Other languages currently display in English.",

    // MARK: Menu bar — File
    "Dự án mới": "New Project",
    "Mở…": "Open…",
    "Mở project khác (tab mới)": "Open Another Project (New Tab)",
    "Lưu": "Save",
    "Lưu thành…": "Save As…",
    "Hoàn tác": "Undo",
    "Làm lại": "Redo",

    // MARK: Menu bar — Phát
    "Phát": "Playback",
    "Phát / Dừng  (Space)": "Play / Pause  (Space)",
    "Lùi 1 giây": "Back 1 second",
    "Tới 1 giây": "Forward 1 second",
    "Lùi 5 giây": "Back 5 seconds",
    "Tới 5 giây": "Forward 5 seconds",

    // MARK: Menu bar — Timeline
    "Timeline": "Timeline",
    "Tách tại vạch đỏ": "Split at playhead",
    "Nhân đôi mục đang chọn": "Duplicate selection",
    "Sao chép clip": "Copy clip",
    "Dán clip vào vạch đỏ": "Paste clip at playhead",
    "Dán thuộc tính (màu/biến hình/fade)": "Paste attributes (color / transform / fade)",
    "Xoá mục đang chọn  (⌫)": "Delete selection  (⌫)",
    "Dời trái 0,1 giây  (,)": "Nudge left 0.1s  (,)",
    "Dời phải 0,1 giây  (.)": "Nudge right 0.1s  (.)",

    // MARK: Menu bar — Lời
    "Lời": "Lyrics",
    "Dòng trước  ([)": "Previous line  ([)",
    "Dòng sau  (])": "Next line  (])",
    "Đặt điểm bắt đầu tại vạch đỏ": "Set start at playhead",
    "Đặt điểm kết thúc tại vạch đỏ": "Set end at playhead",
    "Xoá timing dòng đang chọn": "Clear timing of selected line",

    // MARK: Menu bar — Xem
    "Xem": "View",
    "Phóng to timeline": "Zoom in timeline",
    "Thu nhỏ timeline": "Zoom out timeline",
    "Timeline vừa khung": "Fit timeline to window",
    "Ẩn / hiện lời": "Hide / show lyrics",
    "Tắt / bật tiếng nhạc": "Mute / unmute music",

    // MARK: Hộp thoại lưu / thoát
    "Lưu thay đổi trước khi thoát?": "Save changes before quitting?",
    "Lưu thay đổi trước khi đóng?": "Save changes before closing?",
    "Dự án “%@” có thay đổi chưa được lưu.": "Project “%@” has unsaved changes.",
    "Không lưu": "Don’t Save",
    "Huỷ": "Cancel",
    "Mở project khác trong tab mới": "Open another project in a new tab",

    // MARK: Màn hình Home
    "Hiện trong Finder": "Show in Finder",
    "Bỏ khỏi Gần đây": "Remove from Recent",
    "Xoá": "Delete",
    "Xoá project?": "Delete project?",
    "“%@” sẽ chuyển vào Thùng rác — khôi phục lại được bất cứ lúc nào.":
        "“%@” will be moved to Trash — you can restore it anytime.",
    "Mở project khác…": "Open another project…",
    "Thùng rác": "Trash",
    "Tạo project": "Create project",
    "Tìm project theo tên…": "Search projects by name…",
    "Chưa có project nào": "No projects yet",
    "Bấm “Tạo project” ở trên để bắt đầu.": "Tap “Create project” above to get started.",
    "Nằm ngoài thư mục thư viện — mở gần đây": "Outside the library folder — opened recently",
    "Thùng rác trống": "Trash is empty",
    "Đóng": "Close",
    "Khôi phục": "Restore",
    "Xoá vĩnh viễn": "Delete permanently",
    "Xoá vĩnh viễn?": "Delete permanently?",
    "“%@” sẽ mất hẳn, không khôi phục lại được nữa.":
        "“%@” will be gone for good and cannot be restored.",

    // MARK: Editor — tab bên trái
    "Tạo Karaoke": "Create Karaoke",
    "Nền video": "Video Background",
    "Sửa lời": "Edit Lyrics",
    "Sửa chữ trong từng dòng. Bấm Enter hoặc bấm ra ngoài để cập nhật vào karaoke.":
        "Edit the text of each line. Press Enter or click outside to update the karaoke.",
    "Thêm text": "Add Text",
    "Sóng nhạc": "Audio Waveform",
    "File của bạn": "Your Files",

    // MARK: Editor — thanh công cụ
    "Xuất": "Export",
    "Đang xuất…": "Exporting…",
    "Về Thư viện": "Back to Library",
    "Hoàn tác (⌘Z)": "Undo (⌘Z)",
    "Làm lại (⇧⌘Z)": "Redo (⇧⌘Z)",
    "Mở": "Open",
    "Lưu thành": "Save as",
    "Có thay đổi chưa lưu": "Unsaved changes",
    "Chiều cao": "Height",
    "Bấm đúp để về mặc định": "Double-click to reset",
    "Vị trí phát": "Playback position",
    "Đang dùng kiểu cột mảnh cổ điển — bấm lần nữa để trở về kiểu trước.": "Classic thin bars are on — click again to go back to the previous look.",
    "Độ phân giải": "Resolution",
    "Tuỳ chỉnh %d × %d": "Custom %d × %d",
    "Karaoke đã được tạo. Dán lại lời, sửa lời hoặc đổi file nhạc để tạo lại.": "Karaoke already created. Paste the lyrics again, edit them or change the music to create it again.",
    "Click thước/sóng = tua vạch đỏ · kéo clip lớp đè = dời (kéo dọc đổi làn), kéo mép = cắt · ⌘K = tách tại vạch đỏ · Delete = xoá · double-click sửa · S tách / M gộp ô chữ · ⌘C/⌘V dán · ←→ nudge.": "Click ruler/waveform = move playhead · drag an overlay clip = move (drag vertically to change lane), drag an edge = trim · ⌘K = split at playhead · Delete = remove · double-click to edit · S split / M merge text box · ⌘C/⌘V paste · ←→ nudge.",
    "KARAOKE — tạo karaoke xong sẽ hiện ở đây": "KARAOKE — appears here after you create the karaoke",
    "Đóng tab": "Close tab",
    "Phụ đề": "Subtitles",
    "Nâng cao": "Advanced",
    "Không có tuỳ chọn nâng cao cho video trong suốt.": "No advanced options for transparent video.",
    "Chưa nạp file nhạc.": "No music file loaded.",
    "Không mở được file (đã di chuyển / đổi tên?).": "Can't open the file (moved / renamed?).",
    "Đã chỉnh màu": "Color adjusted",
    "Bấm đúp để về 0": "Double-click to reset to 0",
    "Chọn file nhạc, rồi dán lời hoặc để máy tự tạo lời.": "Choose a music file, then paste lyrics or let the app write them.",
    "Hiện / ẩn vùng an toàn của khung hình": "Show / hide the frame's safe area",
    "Dừng (Space)": "Pause (Space)",
    "Phát (Space)": "Play (Space)",
    "Tên dự án": "Project name",
    "Mở project mới trong tab khác": "Open a new project in another tab",
    "Mở project…": "Open project…",
    "Xuất video / SRT / ASS": "Export video / SRT / ASS",

    // MARK: Editor — tiêu đề thẻ (subCard)
    "Chữ / Text": "Text",

    // MARK: StylePanel — bảng "Chữ"
    "Preset": "Preset",
    "Kiểu chữ": "Text style",
    "Bố cục": "Layout",
    "Màu chữ": "Text color",
    "Viền chữ": "Outline",
    "Đổ bóng": "Shadow",
    "Phát sáng (glow)": "Glow",
    "Khung nền sau chữ": "Background box",
    "Nội dung dòng": "Line text",
    "Dòng %d/%d": "Line %d/%d",
    "Sửa lời dòng": "Edit line text",
    "Chọn một dòng ở danh sách hoặc trên timeline.": "Select a line in the list or on the timeline.",
    "Ẩn preset này": "Hide this preset",
    "của tôi": "mine",
    "Áp dụng": "Apply",
    "Đổi tên…": "Rename…",
    "Lưu kiểu": "Save style",
    "Lưu toàn bộ kiểu chữ hiện tại thành preset dùng lại":
        "Save the whole current text style as a reusable preset",
    "Khôi phục preset mặc định": "Restore default presets",
    "Hiện lại tất cả preset dựng sẵn đã ẩn": "Show all hidden built-in presets",
    "Cỡ chữ": "Font size",
    "Đậm": "Bold",
    "Nghiêng": "Italic",
    "Gạch chân": "Underline",
    "Kiểu hoa/thường": "Letter case",
    "Giữ": "Keep",
    "HOA": "UPPER",
    "thường": "lower",
    "Hoa đầu": "Title",
    "Giãn ký tự": "Letter spacing",
    "Tìm font…": "Search fonts…",
    "Đổi font": "Change font",
    "Chưa hát": "Unsung",
    "Đang hát": "Sung",
    "Màu chữ chưa hát": "Unsung text color",
    "Màu chữ đang hát": "Sung text color",
    "Bật viền": "Outline on",
    "Bật/tắt viền": "Toggle outline",
    "Viền chưa hát": "Unsung outline",
    "Màu viền chưa hát": "Unsung outline color",
    "Viền đang hát": "Sung outline",
    "Màu viền đang hát": "Sung outline color",
    "Độ dày": "Width",
    "Độ dày viền": "Outline width",
    "Bật bóng": "Shadow on",
    "Bật/tắt bóng": "Toggle shadow",
    "Màu bóng": "Shadow color",
    "Độ nhoè": "Blur",
    "Độ nhoè bóng": "Shadow blur",
    "Lệch ngang": "Offset X",
    "Lệch bóng ngang": "Shadow offset X",
    "Lệch dọc": "Offset Y",
    "Lệch bóng dọc": "Shadow offset Y",
    "Bóng vẽ cùng hình dạng & độ bo với viền.": "Shadow follows the outline’s shape and rounding.",
    "Bật glow": "Glow on",
    "Bật/tắt glow": "Toggle glow",
    "Màu glow": "Glow color",
    "Độ toả": "Spread",
    "Độ toả glow": "Glow spread",
    "Bật nền": "Background on",
    "Bật/tắt nền chữ": "Toggle text background",
    "Màu nền": "Background color",
    "Màu nền chữ": "Text background color",
    "Đệm": "Padding",
    "Đệm nền": "Background padding",
    "Bo góc": "Corner radius",
    "Bo góc nền": "Background corner radius",
    "Căn lề": "Alignment",
    "Trái": "Left",
    "Giữa": "Center",
    "Phải": "Right",
    "Vị trí dọc": "Vertical position",
    "Lề trái/phải": "Left/right margin",
    "Khoảng cách dòng": "Line spacing",
    "Chuyển động khối chữ": "Text block motion",
    "%d mốc": "%d keyframes",
    "Xoá hết": "Clear all",
    "Xoá chuyển động chữ": "Clear text motion",
    "Keyframe chữ": "Text keyframe",
    "Cỡ chữ tại mốc": "Font size at keyframe",
    "Cỡ chữ keyframe": "Keyframe font size",
    "Sao chép": "Copy",
    "Dán": "Paste",
    "Dán chuyển động chữ": "Paste text motion",
    "Đảo chuyển động chữ": "Reverse text motion",
    "Đảo chiều": "Reverse",
    "Bấm ◇ để bắt đầu. Rồi dời vạch đỏ + kéo chữ trên màn hình xem trước → tự tạo mốc.":
        "Tap ◇ to start. Then move the playhead and drag the text in the preview — keyframes are added automatically.",
    "Dời vạch đỏ tới lúc khác, kéo chữ trên màn hình xem trước → tự ghi mốc.":
        "Move the playhead elsewhere and drag the text in the preview — a keyframe is recorded automatically.",
    "Kiểu của tôi": "My style",
    "Lưu kiểu chữ hiện tại": "Save current text style",
    "Lưu cả kiểu câu chính và câu nhắc để dùng lại ở bài khác.":
        "Saves both the main and cue line styles to reuse in other songs.",
    "Đổi tên preset": "Rename preset",
    "Đổi": "Rename",
    "Bù trước khi bấm T": "Lead-in before pressing T",

    // MARK: Preview / nền
    "Thấp": "Low",
    "Vừa": "Medium",
    "Cao": "High",
    "Đen": "Dark",
    "Xám": "Gray",
    "Ô caro (trong suốt)": "Checkerboard (transparent)",
    "Ảnh/Video nền": "Background image/video",
    "Kiểu nền": "Background type",
    "Chất lượng xem": "Preview quality",
    "Biểu đồ": "Histogram",
    "Véc-tơ": "Vector",

    // MARK: PlaybackHUD / danh sách dòng lời
    "BẬT": "ON",
    "TẮT": "OFF",
    "Đổi giữa bài gốc và beat (giữ nguyên vị trí)":
        "Switch between the original track and the beat (keeps position)",
    "Bấm “Tạo Karaoke” để tách beat trước": "Tap “Create Karaoke” to extract the beat first",
    "Đang hát: %d": "Now singing: %d",
    "Dòng lời": "Lyric lines",
    "Cuộn theo dòng đang chọn": "Scroll to follow the selected line",
    "Hoàn tác reset timing": "Undo timing reset",
    "Reset toàn bộ timing": "Reset all timing",
    "Chưa có dòng lời. Nhập lời ở trên rồi bấm \"Tách thành dòng\".":
        "No lyric lines yet. Enter lyrics above, then tap \"Split into lines\".",
    "reset timing": "reset timing",
    "Lời dòng": "Line text",
    "Bắt đầu": "Start",
    "Kết thúc": "End",
    "Lấy mốc = chỗ đang phát": "Set to current playback position",
    "chưa gán timing": "no timing yet",

    // MARK: KeyframeControl
    "Xoá mốc tại vạch đỏ": "Remove keyframe at playhead",
    "Thêm mốc tại vạch đỏ": "Add keyframe at playhead",
    "Bắt đầu keyframe (thêm mốc tại vạch đỏ)": "Start keyframes (add one at the playhead)",

    // MARK: KaraokePreview — tên thao tác Hoàn tác
    "Kéo vị trí chữ chính": "Drag main text position",
    "Kéo chữ ngang": "Drag text horizontally",
    "Phóng cỡ chữ": "Scale text size",
    "Keyframe cỡ chữ": "Font size keyframe",
    "Kéo vị trí câu kế": "Drag next-line position",
    "Biến hình lớp đè": "Transform overlay",
    "Kéo sóng nhạc": "Drag waveform",

    // MARK: AppColorPicker — bảng chọn màu / tô
    "Sao chép màu": "Copy color",
    "Dán màu": "Paste color",
    "Về mặc định": "Reset to default",
    "Đơn sắc": "Solid",
    "Tuyến tính": "Linear",
    "Toả tròn": "Radial",
    "Thêm chặng màu": "Add color stop",
    "Bỏ chặng đang chọn": "Remove selected stop",
    "Đảo thứ tự màu": "Reverse color order",
    "Vị trí": "Position",
    "Góc": "Angle",
    "Kiểu tô của tôi": "My fills",
    "Lưu bộ gradient hiện tại": "Save the current gradient",
    "Hút màu trên màn hình": "Pick a color from the screen",
    "Màu của tôi": "My colors",
    "Lưu màu hiện tại vào “Màu của tôi”": "Save the current color to “My colors”",
    "Xoá khỏi Màu của tôi": "Remove from My colors",

    // MARK: FilePanels — tiêu đề hộp thoại
    "Mở dự án karaoke": "Open karaoke project",
    "Lưu dự án karaoke": "Save karaoke project",
    "Xuất video chữ karaoke": "Export karaoke text video",
    "Xuất video karaoke": "Export karaoke video",
    "Xuất phụ đề SRT": "Export SRT subtitles",
    "Xuất phụ đề karaoke ASS": "Export ASS karaoke subtitles",
    "Lưu vocal đã tách": "Save separated vocal",
    "Chọn file lời bài hát": "Choose a lyrics file",
    "Chọn ảnh nền": "Choose a background image",
    "Chọn LUT (.cube)": "Choose a LUT (.cube)",
    "Nhập file vào kho media": "Import files to the media library",
    "Chọn video nền": "Choose a background video",
    "Chọn file nhạc": "Choose a music file",
    "Không mở được file:": "Couldn’t open the file:",
    "Không lưu được file:": "Couldn’t save the file:",
    "Không đọc được nội dung file:": "Couldn’t read the file contents:",

    // MARK: TimelineEditor + ContentView (lô "làm hết")
    "Bật tiếng karaoke": "Unmute karaoke",
    "Tắt tiếng karaoke": "Mute karaoke",
    "Tắt / bật tiếng cả bản karaoke": "Mute / unmute the whole karaoke track",
    "Bật tiếng nhạc": "Unmute music",
    "Tắt tiếng nhạc": "Mute music",
    "Nhạc": "Music",
    "Hiện lời": "Show lyrics",
    "Ẩn lời": "Hide lyrics",
    "Ẩn / hiện lớp chữ karaoke": "Show / hide the karaoke text layer",
    "Lớp đè %d": "Overlay %d",
    "Tắt / bật tiếng cả làn": "Mute / unmute the whole lane",
    "Ẩn / hiện cả làn": "Show / hide the whole lane",
    "Khoá / mở khoá cả làn": "Lock / unlock the whole lane",
    "đang phân tích sóng…": "analyzing waveform…",
    "Tách lớp đè tại vạch đỏ (⌘K)": "Split overlay at playhead (⌘K)",
    "Nhân đôi lớp đè": "Duplicate overlay",
    "Xoá lớp đè": "Delete overlay",
    "Thu nhỏ (⌘−)": "Zoom out (⌘−)",
    "Phóng to (⌘=)": "Zoom in (⌘=)",
    "Vừa khung": "Fit to window",
    "Click thước/sóng = tua vạch đỏ · kéo clip lớp đè = dời (kéo dọc đổi làn), kéo mép = cắt · ✂️ hoặc ⌘K = tách tại vạch đỏ · Delete = xoá · double-click sửa · S tách / M gộp ô chữ · ⌘C/⌘V dán · ←→ nudge.": "Click ruler/waveform = move playhead · drag an overlay clip = move (drag vertically to change lane), drag an edge = trim · ✂️ or ⌘K = split at playhead · Delete = remove · double-click to edit · S split / M merge text box · ⌘C/⌘V paste · ←→ nudge.",
    "Chưa có nhạc vẫn dùng được: click thước để tua vạch đỏ, ▶ để chạy thử. Kéo nhạc/ảnh/video từ “File của bạn” xuống các làn bên dưới.": "Works without music: click the ruler to move the playhead, ▶ to preview. Drag music/images/video from “Your Files” down to the lanes below.",
    "Chữ": "Text",
    "CHẾ ĐỘ SONG CA — bấm khối câu để chọn người hát": "DUET MODE — tap a line block to choose the singer",
    "★ KARAOKE — tạo karaoke xong sẽ hiện ở đây": "★ KARAOKE — appears here after you create the karaoke",
    "Kéo LÊN thả vào chỗ trống trong hàng lời": "Drag UP and drop into an empty spot in the lyric row",
    "Kéo LÊN thả vào TRONG 1 dòng (chỗ còn trống)": "Drag UP and drop INTO a line (an empty spot)",
    "✕ Huỷ": "✕ Cancel",
    "Kéo ảnh / video / nhạc từ “File của bạn” xuống đây": "Drag images / video / music from “Your Files” here",
    "＋ chuột phải để dán lời": "＋ right-click to paste lyrics",
    "Đổi tên clip": "Rename clip",
    "Chuyển cảnh mờ với clip trước (0,5s)": "Crossfade with the previous clip (0.5s)",
    "Tách tại đây": "Split here",
    "Nhân đôi": "Duplicate",
    "Dán thuộc tính vào clip này": "Paste attributes onto this clip",
    "Nhân đôi dòng": "Duplicate line",
    "Xoá dòng": "Delete line",
    " · karaoke vào ở %@": " · karaoke starts at %@",
    "%d dòng có timing sẽ được xuất. (%d/%d dòng đã gán)": "%d timed lines will be exported. (%d/%d lines set)",
    "%d lớp đang chọn": "%d layers selected",
    "(%d lớp)": "(%d layers)",
    "(trống)": "(empty)",
    "= đang phát": "= playhead",
    "Beat + Vocal của bạn": "Your Beat + Vocal",
    "Bạn có bài nhạc, hay có sẵn Beat + Vocal riêng?": "Do you have a song, or separate Beat + Vocal files?",
    "Bấm khối câu trên timeline rồi chọn icon · bấm “Song ca” lần nữa để thoát": "Tap a line block on the timeline, then pick an icon · tap “Duet” again to exit",
    "Bấm để thêm ở vạch đỏ, hoặc KÉO nút này thả xuống làn lớp đè trên timeline. Lớp chữ hoạt động như lớp ảnh: kéo–giãn–xoay trên màn hình xem trước, chỉnh bên phải.": "Tap to add at the playhead, or DRAG this button onto an overlay lane on the timeline. A text layer works like an image layer: drag–scale–rotate in the preview, edit on the right.",
    "Bật tiếng của clip video": "Enable this video clip’s audio",
    "Bắt đầu làm karaoke": "Start making karaoke",
    "Bỏ nhóm": "Ungroup",
    "Bỏ nhạc": "Remove music",
    "Bỏ nền hình": "Remove background media",
    "Bỏ đánh dấu cả bài": "Clear marks for the whole song",
    "Bỏ đánh dấu dòng này": "Clear mark on this line",
    "Bỏ đánh dấu người hát cả bài": "Clear singer marks for the whole song",
    "Bỏ": "Remove",
    "Canh xong nhưng không ra dòng nào — kiểm tra lại lời / nhạc.": "Alignment finished but produced no lines — check the lyrics / audio.",
    "Chia đều chữ": "Distribute words evenly",
    "Cho CẢ BÀI hiện sớm hơn 0,25 giây": "Make the WHOLE song appear 0.25s earlier",
    "Cho DÒNG đang chọn hiện sớm hơn 0,25 giây": "Make the selected LINE appear 0.25s earlier",
    "Chuyển cảnh": "Transition",
    "Chuyển động": "Motion",
    "Chưa copy câu nào (chọn câu rồi ⌘C).": "No verse copied yet (select a verse then ⌘C).",
    "Chưa có beat. Bấm \"Tạo beat\" ở trên, hoặc chọn lại âm thanh khác.": "No beat yet. Tap \"Create beat\" above, or pick another audio file.",
    "Chưa có dòng nào có timing để export.": "No timed lines to export.",
    "Chưa có file audio/vocal để dò nhịp.": "No audio/vocal file to detect the beat.",
    "Chưa có file nhạc.": "No music file yet.",
    "Chưa có. Thêm logo hoặc ảnh graded để đè lên video.": "None yet. Add a logo or graded image to overlay on the video.",
    "Chỉ nhận file nhạc (MP3, WAV, M4A…).": "Only music files are accepted (MP3, WAV, M4A…).",
    "Chỉnh fade lớp đè": "Adjust overlay fade",
    "Chỉnh kỹ hơn nền (phóng to, lệch, độ mờ) ở tab \"Xuất\".": "Fine-tune the background (zoom, offset, opacity) in the \"Export\" tab.",
    "Chỉnh màu nền": "Adjust background color",
    "Chỉnh sóng nhạc": "Adjust waveform",
    "Chỉnh điểm bắt đầu": "Adjust start point",
    "Chỉnh điểm kết thúc": "Adjust end point",
    "Chọn cả nhóm": "Select whole group",
    "Chọn file .cube…": "Choose a .cube file…",
    "Chọn file nhạc (MP3 / WAV)…": "Choose a music file (MP3 / WAV)…",
    "Chọn lại…": "Choose again…",
    "Chọn nền ở tab **Nền video**, thêm chữ ở tab **Thêm text**, bật sóng nhạc ở tab **Sóng nhạc**. Thêm ảnh / video / nhạc đè ở tab **File của bạn**.": "Choose a background in the **Video Background** tab, add text in **Add Text**, enable the waveform in **Audio Waveform**. Add overlay images / video / music in **Your Files**.",
    "Chọn nền ở thanh \"Nền:\" phía trên Preview (nút Ảnh nền… / Video nền…).": "Choose a background in the \"Background:\" bar above the preview (Image… / Video… buttons).",
    "Chọn…": "Choose…",
    "Chữ ra": "Text out",
    "Chữ sớm +0.25 (cả bài)": "Text earlier +0.25 (whole song)",
    "Chữ sớm +0.25 (dòng)": "Text earlier +0.25 (line)",
    "Chữ vào": "Text in",
    "Clip tiếng — trộn kèm bài hát chính khi phát thử và khi xuất video.": "Audio clip — mixed with the main song during preview and video export.",
    "Clipboard trống — hãy copy lời trước.": "Clipboard is empty — copy the lyrics first.",
    "Cắt lớp đè": "Trim overlay",
    "Cỡ gốc": "Original size",
    "Dài ~%@": "Length ~%@",
    "Dán chuyển động sóng": "Paste waveform motion",
    "Dán chuyển động": "Paste motion",
    "Dán clip": "Paste clip",
    "Dán câu": "Paste verse",
    "Dán lời câu mới": "Paste new verse lyrics",
    "Dán lời theo thứ tự hát, mỗi câu 1 dòng. Cách các đoạn (phiên khúc, điệp khúc, đoạn cầu…) bằng MỘT dòng trống. Đoạn nào hát lại chỉ cần viết MỘT lần — máy tự tìm và nhân bản cho đủ.": "Paste the lyrics in singing order, one line per phrase. Separate sections (verse, chorus, bridge…) with ONE blank line. Write a repeated section only ONCE — the app finds and duplicates it as needed.",
    "Dán thuộc tính clip": "Paste clip attributes",
    "Dán thông số màu": "Paste color settings",
    "Dùng 2 file này": "Use these 2 files",
    "Dùng beat + vocal": "Use beat + vocal",
    "Dải này về 0": "Reset this band to 0",
    "Dời clip Karaoke": "Move karaoke clip",
    "Dời câu trên timeline": "Move verse on timeline",
    "Dời lớp đè": "Move overlay",
    "File .mov nền trong suốt, chỉ có sóng nhạc — chất lượng theo ô 'Chất lượng' ở trên. Ghép ở phần mềm khác.": "A transparent .mov with only the waveform — quality follows the 'Quality' setting above. Composite it in another app.",
    "File ASS không có dòng hợp lệ.": "The ASS file has no valid lines.",
    "File SRT không có dòng hợp lệ.": "The SRT file has no valid lines.",
    "Giữa khung": "Center in frame",
    "Glow theo màu gốc": "Glow follows source color",
    "Gom nhóm lớp": "Group layers",
    "Gom thành nhóm": "Group",
    "HIỆU ỨNG": "EFFECTS",
    "Hiện cả nhóm": "Show whole group",
    "Hiện dần": "Fade in",
    "Hiệu ứng \\kf quét sáng từng chữ. Dùng timing từng chữ nếu có, không thì chia đều. Mở bằng Aegisub / VLC.": "\\kf effect wipes each word. Uses per-word timing if available, otherwise splits evenly. Open with Aegisub / VLC.",
    "Hoà trộn": "Blend",
    "Hoàn tác xoá timing": "Undo clear timing",
    "Hoặc": "Or",
    "Import nhạc": "Import music",
    "Keyframe sóng": "Waveform keyframe",
    "Khoá / mở khoá lớp đè": "Lock / unlock overlay",
    "Khoá cả nhóm": "Lock whole group",
    "Khoá lại để không kéo/sửa nhầm": "Lock so it can’t be dragged/edited by mistake",
    "Khoảng 30–60 giây.": "About 30–60 seconds.",
    "Khung hình": "Frame size",
    "Không dò đủ nhịp trong đoạn câu này (nhạc to / giọng nhỏ).": "Not enough beats detected in this passage (music too loud / vocal too quiet).",
    "Không ghi được file .ass: \\(error.localizedDescription)": "Could not write the .ass file: \\(error.localizedDescription)",
    "Không ghi được file SRT: \\(error.localizedDescription)": "Could not write the SRT file: \\(error.localizedDescription)",
    "Không tìm thấy file nhạc": "Music file not found",
    "Không đọc được file \\(url.lastPathComponent).": "Could not read file \\(url.lastPathComponent).",
    "Khớp chữ vào nhịp": "Snap words to the beat",
    "Kiểu chạy": "Easing",
    "Kiểu chữ karaoke": "Karaoke text style",
    "Kiểu keyframe": "Keyframe easing",
    "Kiểu lớp chữ: \\(pr.name)": "Text layer style: \\(pr.name)",
    "Kiểu màu": "Color style",
    "Kiểu": "Style",
    "Kéo 1 món xuống timeline: ảnh/video → lớp đè · nhạc → làn lớp đè thành clip tiếng.": "Drag an item onto the timeline: image/video → overlay · music → overlay lane as an audio clip.",
    "Kéo bất kỳ clip nào để dời cả nhóm · ⌫ để xoá cả nhóm · ⌘/Shift+bấm để thêm/bớt.": "Drag any clip to move the whole group · ⌫ to delete the group · ⌘/Shift+click to add/remove.",
    "Kéo dòng trên timeline": "Drag line on timeline",
    "Kéo trên timeline để dời / đổi làn · kéo mép để cắt độ dài.": "Drag on the timeline to move / change lane · drag an edge to trim length.",
    "Kéo xuống timeline để đặt lên video, hoặc bấm chuột phải": "Drag onto the timeline to place over the video, or right-click",
    "Kéo ảnh / nhạc / video vào đây, hoặc bấm “Nhập file…”.": "Drag images / music / video here, or tap “Import files…”.",
    "Kéo–giãn–xoay trên màn hình xem trước · bấm đúp chữ để sửa nhanh.": "Drag–scale–rotate in the preview · double-click the text for a quick edit.",
    "Kéo–giãn–xoay trực tiếp trên màn hình xem trước. Thời điểm hiện / mất chỉnh ở timeline.": "Drag–scale–rotate directly in the preview. Set the show / hide times on the timeline.",
    "Kết thúc câu": "End verse",
    "LUT 3D .cube (áp trong sRGB).": "3D LUT .cube (applied in sRGB).",
    "Lưu kiểu hiện tại…": "Save current style…",
    "Lưu kiểu lớp chữ": "Save text layer style",
    "Lưu preset màu": "Save color preset",
    "Lưu preset màu…": "Save color preset…",
    "Lấp 2 bên bằng ảnh mờ (không cắt cúp)": "Fill the sides with a blurred image (no cropping)",
    "Lớp đè": "Overlay",
    "MÀU SẮC": "COLOR",
    "MÀU": "COLOR",
    "Màu \\(role.label)": "\\(role.label) color",
    "Một số dòng đã có timing. Thao tác này tạo danh sách dòng mới và xoá timing hiện có.": "Some lines already have timing. This creates a new line list and clears the existing timing.",
    "Mờ dần": "Fade out",
    "Mở bảng chỉnh ở cột bên phải": "Open the editor panel on the right",
    "Mở khoá nhóm": "Unlock group",
    "Mở thư mục": "Open folder",
    "Nhân bản câu": "Duplicate verse",
    "Nhạc vào từ": "Music starts at",
    "Nhập SRT / ASS…": "Import SRT / ASS…",
    "Nhập file": "Import",
    "Nhập file vào kho": "Import files to library",
    "Nhập file…": "Import files…",
    "Kéo và thả video, ảnh, nhạc vào đây": "Drag and drop videos, photos, and audio files here",
    "Nhập lại lời": "Re-enter lyrics",
    "Nhập lời từ \\(source)": "Import lyrics from \\(source)",
    "Nhỏ dần": "Fade out",
    "Nạp lời từ file": "Load lyrics from file",
    "Nền hình (Mode C)": "Background media (Mode C)",
    "Nhóm: %@": "Group: %@",
    "Xoá %d lớp": "Delete %d layers",
    "Phủ kín": "Fill",
    "Preset màu": "Color presets",
    "Sao chép chuyển động": "Copy motion",
    "Sao chép thông số màu": "Copy color settings",
    "Sóng nhạc keyframe": "Waveform keyframe",
    "Sửa chữ trên timeline": "Edit text on timeline",
    "Sửa lớp đè": "Edit overlay",
    "Sửa điểm bắt đầu": "Edit start point",
    "Sửa điểm kết thúc": "Edit end point",
    "Sửa": "Edit",
    "Thay & xoá timing": "Replace & clear timing",
    "Thay toàn bộ dòng lời?": "Replace all lyric lines?",
    "Thêm 1 dòng lời mới": "Add a new lyric line",
    "Thêm 1 lớp chữ": "Add a text layer",
    "Thêm 1 ô chữ vào dòng đang chọn": "Add a text box to the selected line",
    "Thêm BOM UTF-8": "Add UTF-8 BOM",
    "Thêm chữ": "Add text",
    "Thêm câu mới": "Add new verse",
    "Thêm dòng": "Add line",
    "Thêm giờ chờ (cả bài)": "Add wait time (whole song)",
    "Thêm giờ chờ (dòng này)": "Add wait time (this line)",
    "Thêm lớp chữ": "Add text layer",
    "Thêm lớp đè": "Add overlay",
    "To dần": "Fade in",
    "Tuỳ chỉnh": "Custom",
    "Tách lại": "Separate again",
    "Tách lớp đè": "Split overlay",
    "Tách thành dòng": "Split into lines",
    "Tạo Karaoke Chất Lượng": "Create High-Quality Karaoke",
    "Tạo Karaoke bằng AI": "Create Karaoke with AI",
    "Tạo beat": "Create beat",
    "Tạo nhanh Karaoke": "Quick Karaoke",
    "Tắt = ảnh nằm DƯỚI chữ (dùng để tô màu / graded video)": "Off = the image sits UNDER the text (for color / graded video)",
    "Tắt tiếng clip này": "Mute this clip",
    "Tự chuyển động nhẹ (Ken Burns)": "Subtle auto motion (Ken Burns)",
    "Tự reset câu bấm T dở dang": "Auto-reset the unfinished tap-T verse",
    "Video nền…": "Background video…",
    "Video trong suốt: .mov ProRes 4444 (chất lượng cao, xuất nhanh — file lớn).": "Transparent video: .mov ProRes 4444 (high quality, fast export — large file).",
    "Video vào từ": "Video starts at",
    "Vào câu": "Enter verse",
    "Vạch an toàn": "Safe guides",
    "Vẽ theo nhạc GỐC bạn bỏ vào. Mặc định full bề ngang — chỉnh cỡ / vị trí bên dưới.": "Drawn from the ORIGINAL audio you added. Full width by default — adjust size / position below.",
    "Về 0": "Reset to 0",
    "Về gốc": "Reset",
    "Xem Trước / Sau (tạm tắt chỉnh màu)": "Before / After (temporarily disable color)",
    "Xoá chuyển động sóng": "Clear waveform motion",
    "Xoá chuyển động": "Clear motion",
    "Xoá câu": "Delete verse",
    "Xoá file khỏi kho": "Remove file from library",
    "Xoá hết chuyển động": "Clear all motion",
    "Xoá khỏi kho": "Remove from library",
    "Xoá kiểu": "Delete style",
    "Xoá lớp này": "Delete this layer",
    "Xoá preset": "Delete preset",
    "Xoá timing dòng": "Clear line timing",
    "Xoá ô lời": "Clear lyrics box",
    "Xuất .ass (karaoke quét chữ)": "Export .ass (word-wipe karaoke)",
    "Xuất .ass…": "Export .ass…",
    "Xuất .mov ProRes (nền màu đục — cho dựng phim)": "Export .mov ProRes (opaque background — for editing)",
    "Xuất SRT": "Export SRT",
    "Xuất SRT…": "Export SRT…",
    "Xuất riêng sóng nhạc (nền trong suốt)…": "Export waveform only (transparent background)…",
    "Xuất video": "Export video",
    "Xuất video…": "Export video…",
    "kéo file vào, hoặc bấm Chọn": "drag a file in, or tap Choose",
    "ÁNH SÁNG": "LIGHT",
    "Âm thanh trong video": "Audio in the video",
    "Đang %@…": "%@…",
    "Đang dùng beat + vocal bạn đưa vào. Bấm \"Bỏ\" ở phần dưới trước nếu muốn dùng file nhạc thường.": "Using the beat + vocal you provided. Tap \"Remove\" below first if you want to use a normal music file.",
    "Đang hiện": "Visible",
    "Đang khoá — bấm để mở, kéo/sửa được lại": "Locked — tap to unlock and edit again",
    "Đang mở phần “Chỉnh sửa”…": "Opening the “Edit” section…",
    "Đang tách nhạc…": "Separating audio…",
    "Đang xem BẢN GỐC (chỉnh màu tạm tắt).": "Viewing the ORIGINAL (color adjustments off).",
    "Đang xử lý…": "Working…",
    "Đang ẩn": "Hidden",
    "Đã %@ xong": "%@ done",
    "Đã có beat cho bài này.": "This song already has a beat.",
    "Đã khoá — mở khoá ở danh sách bên trái để sửa": "Locked — unlock in the list on the left to edit",
    "Đã xuất: %@": "Exported: %@",
    "Đè lên trên chữ karaoke": "Above the karaoke text",
    "Đè lên trên chữ": "Above the text",
    "Đường cong về thẳng": "Reset curve to linear",
    "Đảo chuyển động": "Reverse motion",
    "Đặt vào timeline (ở mốc đang phát)": "Place on timeline (at the playhead)",
    "Đặt điểm bắt đầu": "Set start point",
    "Đặt điểm kết thúc": "Set end point",
    "Đối xứng 2 bên": "Mirror both sides",
    "Đổi BOM": "Toggle BOM",
    "Đổi FPS": "Change FPS",
    "Đổi khung hình": "Change frame size",
    "Đổi màu vai \\(role.label)": "Change \\(role.label) color",
    "Đổi tên dự án": "Rename project",
    "Đổi tên nhóm": "Rename group",
    "Đổi tên": "Rename",
    "Đổi ảnh / video": "Change image / video",
    "Đổi ảnh lớp đè": "Change overlay image",
    "Đổi ảnh…": "Change image…",
    "Độ mờ keyframe": "Opacity keyframe",
    "Ảnh / video / logo: kéo xuống timeline để đè lên video.": "Image / video / logo: drag onto the timeline to overlay the video.",
    "Ảnh nền…": "Background image…",
    "Ảnh/Video HDR — đã hạ về SDR để hiển thị & xuất.": "HDR image/video — tone-mapped to SDR for display & export.",
    "Ẩn / hiện lớp đè": "Show / hide overlay",
    "Ẩn cả nhóm": "Hide whole group",
    "Ẩn": "Hide",
    "“Chất lượng” tách nhạc sạch hơn nhưng lâu hơn nhiều.": "“High quality” separates audio more cleanly but is much slower.",
    "…hoặc kéo file nhạc từ Finder thả vào đây.": "…or drag a music file from Finder and drop it here.",
    "⚠︎ Chưa nạp file nhạc.": "⚠︎ No music file loaded.",
    "⚠︎ Không mở được file (đã di chuyển / đổi tên?).": "⚠︎ Could not open the file (moved / renamed?).",
    "＋ Ảnh / logo…": "＋ Image / logo…",
    "Nhạc gốc (có lời)": "Original song (with vocals)",
    "Chỉ beat (không lời)": "Beat only (no vocals)",
    "Không tiếng": "No audio",
    "Cả bài nhạc": "Whole song",
    "Beat + Vocal riêng": "Separate Beat + Vocal",
    "Nhập file audio": "Import audio file",
    "Dán lời & tạo karaoke": "Paste lyrics & create karaoke",
    "Kéo file nhạc vào ô 'File của bạn' (cột trái) hoặc thả xuống timeline.": "Drag a music file into \"Your Files\" (left column) or drop it on the timeline.",
    "Sang tab 'Tạo Karaoke' → dán lời bài hát.": "Go to the \"Create Karaoke\" tab → paste the song lyrics.",
    "Bấm tạo karaoke, rồi tinh chỉnh trên timeline.": "Tap to create karaoke, then fine-tune on the timeline.",
    "phân tích nhạc": "analyze audio",
    "tạo karaoke": "create karaoke",

    // MARK: Sửa lỗi rà soát 2026-09-10 (sóng nhạc, enum label, colorSlider, …)
    "Bão hoà": "Saturation",
    "Bóng dọc": "Shadow Y",
    "Bóng ngang": "Shadow X",
    "Bóng đổ (alpha 0 = tắt)": "Shadow (alpha 0 = off)",
    "Bấm ◇ để bắt đầu. Rồi dời vạch đỏ + chỉnh cỡ/vị trí/độ mờ (hoặc kéo sóng trên màn hình xem trước) → tự tạo mốc.": "Tap ◇ to start. Then move the playhead + adjust size/position/opacity (or drag the waveform in the preview) — keyframes are added automatically.",
    "Bấm ◇ để bắt đầu. Rồi dời vạch đỏ + chỉnh lớp → app tự tạo mốc.": "Tap ◇ to start. Then move the playhead + adjust the layer — keyframes are added automatically.",
    "Bật lên": "Pop",
    "Bật sóng nhạc": "Enable waveform",
    "Bật tiếng cả làn": "Unmute whole lane",
    "Bề rộng ngắt dòng": "Wrap width",
    "Bỏ đánh dấu người hát": "Clear singer mark",
    "Chi tiết": "Details",
    "Chấm nảy": "Bouncing dots",
    "Chấm sáng ở ngọn (alpha > 0 để bật)": "Tip highlight (alpha > 0 to enable)",
    "Chậm dần cuối": "Ease out",
    "Cách dòng": "Line spacing",
    "Cầu vồng theo cột": "Rainbow per bar",
    "Cột chia đốt": "Segmented bars",
    "Cột từ đáy": "Bars from bottom",
    "Cột đối xứng": "Mirrored bars",
    "Cỡ ngang": "Width",
    "Dải màu": "Color range",
    "Dải sóng đầy": "Filled area",
    "Dọc (gốc→ngọn)": "Vertical (base→tip)",
    "Dời ngang": "Offset X",
    "Dời sớm": "Shift earlier",
    "Dời trễ": "Shift later",
    "Dời vạch đỏ tới chỗ khác, kéo–giãn–xoay lớp trên màn hình xem trước → tự ghi mốc.": "Move the playhead elsewhere, drag–scale–rotate the layer in the preview — a keyframe is recorded automatically.",
    "Dời vạch đỏ tới lúc khác, chỉnh cỡ/vị trí/độ mờ → tự ghi mốc.": "Move the playhead elsewhere, adjust size/position/opacity — a keyframe is recorded automatically.",
    "Giãn chữ": "Letter spacing",
    "HSL / CHỌN MÀU": "HSL / SELECTIVE",
    "Hiện cả làn": "Show whole lane",
    "Hiệu ứng chữ ra": "Text-out effect",
    "Hiệu ứng chữ vào": "Text-in effect",
    "Ken Burns nền": "Background Ken Burns",
    "Khe cột": "Bar gap",
    "Khoá cả làn": "Lock whole lane",
    "Khoá/mở nhóm": "Lock/unlock group",
    "Không": "None",
    "Khối tròn nhấp nhô": "Pulsing blob",
    "Lệch nền dọc": "Background offset Y",
    "Lệch nền ngang": "Background offset X",
    "Lớp đè 1": "Overlay 1",
    "Lục": "Green",
    "Màu gốc": "Base color",
    "Màu ngọn": "Tip color",
    "Màu sắc": "Color",
    "Màu viền": "Outline color",
    "Mép hát mềm": "Soft wipe edge",
    "Mép vệt hát loang mềm": "Soft wipe edge bleed",
    "Mượt 2 đầu": "Ease in-out",
    "Mở khoá cả làn": "Unlock whole lane",
    "Ngang (trái→phải)": "Horizontal (left→right)",
    "Nhiệt độ": "Temp",
    "Nhoè bóng": "Shadow blur",
    "Nhóm": "Group",
    "Nâng lên": "Raise",
    "Nét": "Stroke",
    "Nảy": "Bounce",
    "Nền mờ lấp cạnh": "Blurred edge fill",
    "Nền sau chữ (alpha 0 = tắt)": "Text background (alpha 0 = off)",
    "Nữ": "Female",
    "Nam": "Male",
    "Song ca": "Duet",
    "Phát sáng / glow (alpha 0 = tắt)": "Glow (alpha 0 = off)",
    "Phóng nền": "Zoom background",
    "Phóng to": "Zoom",
    "Phơi sáng": "Exposure",
    "Sáng (glow)": "Glow",
    "Sáng nổi": "Highlights",
    "Sáng": "Lightness",
    "Sóng nhạc: BẬT": "Waveform: ON",
    "Sóng nhạc: TẮT": "Waveform: OFF",
    "Sắc màu": "Tint",
    "Số cột": "Bar count",
    "Số đốt": "Segment count",
    "Thời lượng (×1s)": "Duration (×1s)",
    "Thời lượng hiệu ứng": "Effect duration",
    "Trượt lên": "Rise",
    "Tông màu": "Hue",
    "Tương phản": "Contrast",
    "Tắt sóng nhạc": "Disable waveform",
    "Tắt tiếng cả làn": "Mute whole lane",
    "Tốc độ quét chữ": "Wipe speed",
    "Tối góc": "Vignette",
    "Vòng toả tia": "Radial rays",
    "Vùng tối": "Shadows",
    "Văn bản": "Text",
    "Vệt sáng chạy theo mép hát": "Light streak follows the wipe edge",
    "Vệt sáng mép hát": "Wipe-edge light streak",
    "Xem trước": "Preview",
    "Xoay màu": "Color rotation",
    "Điểm trắng": "Whites",
    "Điểm đen": "Blacks",
    "ĐƯỜNG CONG": "CURVES",
    "Đường sóng": "Wave line",
    "Đặt tiếng lên timeline": "Place audio on timeline",
    "Đặt video lên timeline": "Place video on timeline",
    "Đặt ảnh từ kho lên timeline": "Place library image on timeline",
    "Đều": "Linear",
    "Đỏ": "Red",
    "Chung": "Master",
    "Lam": "Blue",
    "Độ mượt": "Smoothing",
    "Độ mạnh": "Strength",
    "Độ mờ nền": "Background opacity",
    "Độ mờ": "Opacity",
    "Độ nhạy": "Sensitivity",
    "Độ rực": "Vibrance",
    "Ẩn cả làn": "Hide whole lane",
    "Ẩn xem trước": "Hide preview",
    "Ẩn/hiện nhóm": "Show/hide group",
    "🎤  Vocal (chỉ giọng)": "🎤  Vocal (voice only)",
    "Vocal (chỉ giọng)": "Vocal (voice only)",
    "🥁  Beat (không lời)": "🥁  Beat (no vocals)",
    "Beat (không lời)": "Beat (no vocals)",
    "Xong": "Done",

    // MARK: Tab bảng sửa (2026-09-10)
    "Nội dung": "Content",
    "Màu": "Color",
    "Hiệu ứng": "Effects",
    "Biến hình": "Transform",

    // MARK: Sóng nhạc — preset cổ điển + nền zoom theo nhạc (2026-09-11)
    "Cột mảnh cổ điển": "Classic thin bars",
    "Đổi sang kiểu cột trắng mảnh, dày, gọn gàng — kiểu spectrum cổ điển hay dùng trong video nhạc.":
        "Switches to thin, dense white bars — the classic spectrum look used in many music videos.",
    "Đổi kiểu sóng nhạc": "Change waveform style",
    "Nền tự zoom theo nhạc": "Background zooms to the music",
    "Bật zoom theo nhạc": "Enable zoom to music",
    "Cần chọn nền ảnh/video ở tab \"Nền video\" trước.": "Choose a background image/video in the \"Video Background\" tab first.",
    "Mức zoom": "Zoom amount",
    "Nền phóng to nhẹ theo tiếng nhạc, tự mượt lại — không giật.":
        "The background zooms in slightly with the music and eases back smoothly — no jitter.",
    "Nền zoom theo nhạc": "Zoom background to music",
    "Mức zoom theo nhạc": "Zoom-to-music amount",
    "Lưu (⌘S)": "Save (⌘S)",

    // MARK: Hiệu ứng Bass nền (2026-09-12, dời từ tab Sóng nhạc sang tab Nền video)
    "Hiệu ứng Bass nền": "Background bass effect",
    "Mức bass": "Bass amount",
    "Chọn ảnh/video nền bên dưới để dùng hiệu ứng này.": "Choose a background image/video below to use this effect.",
    "Nền phóng to nhẹ theo tiếng bass, tự mượt lại — không giật.":
        "The background zooms in slightly with the bass and eases back smoothly — no jitter.",
    "Đã nhập %d dòng kèm timing từ %@.": "Imported %d timed lines from %@.",
    "Đã nạp lời từ %@. Bấm \"Tách thành dòng\".": "Loaded lyrics from %@. Tap \"Split into lines\".",
    "Đã xuất %d dòng ra %@": "Exported %d lines to %@",
    "Đã xuất phụ đề karaoke ra %@": "Exported karaoke subtitles to %@",

    // MARK: Tự động lấy lời (Local Auto Lyrics) — thử nghiệm
    "Tự động lấy lời": "Auto Lyrics",
    "Tự động lấy lời (thử nghiệm)": "Auto Lyrics (experimental)",
    "Thử nghiệm": "Experimental",
    "Máy nghe bài hát ngay trên máy này để đoán lời; bạn luôn xem lại trước khi dùng. Tắt để ẩn nút này.":
        "Listens to the song on this Mac to guess the lyrics; you always review before using them. Turn off to hide this button.",
    "Máy nghe bài hát để đoán lời (thử nghiệm) — bạn xem lại rồi mới dùng": "Listens to the song to guess the lyrics (experimental) — you review before using them",
    "Máy nghe bài hát trong máy để đoán lời — bạn xem lại rồi mới dùng.": "Listens to the song on this Mac to guess the lyrics — you review before using them.",
    "Khôi phục lời trước đó": "Restore previous lyrics",
    "Đang chuẩn bị…": "Preparing…",
    "Đang nạp bộ nhận dạng…": "Loading the recognizer…",
    "Đang nhận dạng lời… %d / %d": "Recognizing lyrics… %d / %d",
    "Đang kiểm tra lời… %d / %d": "Checking lyrics… %d / %d",
    "Đang kiểm tra lời…": "Checking lyrics…",
    "Đang kiểm tra lại đoạn chưa chắc… %d / %d": "Re-checking uncertain parts… %d / %d",
    "Đang hoàn thiện…": "Finishing…",
    "Chưa có file nhạc trong project.": "This project has no audio file yet.",
    "Chưa có bản tách giọng hát của bài này.": "There is no separated vocal track for this song yet.",
    "Chưa tìm thấy bộ nhận dạng lời trên máy này.": "The lyric recognizer was not found on this Mac.",
    "Không thấy helper nhận dạng lời trong app.": "The recognition helper is missing from the app.",
    "Đã tìm: %@": "Looked in: %@",
    "Bộ nhận dạng lời trong app bị thiếu hoặc hỏng. Hãy cài lại KaraokeMaker.": "The lyric recognizer inside the app is missing or damaged. Please reinstall KaraokeMaker.",
    "Thiếu mô hình nhận dạng lời.": "A recognition model is missing.",
    "Bộ xử lý của máy không dùng được cho việc này.": "This Mac's processor cannot be used for this.",
    "Không đọc được file nhạc.": "Could not read the audio file.",
    "Nhận dạng lời gặp lỗi.": "Recognition failed.",
    "Kết quả nhận dạng không hợp lệ.": "The recognition result is invalid.",
    "Không có file kết quả.": "No result file.",
    "Không đủ bộ nhớ.": "Not enough memory.",
    "Không nhận ra lời nào trong bài này (có thể đây là bản nhạc không lời).": "No lyrics were recognized in this song (it may be instrumental).",
    "Hủy và đóng": "Cancel and close",
    "Phân tích nhạc": "Analyze music",
    "Dùng lời này": "Use these lyrics",
    "Lời hiện có của project KHÔNG bị thay đổi.": "The project's existing lyrics are NOT changed.",
    "Bạn vẫn dùng app bình thường trong lúc chờ.": "You can keep using the app while you wait.",
    "“Dùng lời này” sẽ đưa bản nháp vào ô lời (lời cũ có nút khôi phục). Chưa có gì đổi cho tới lúc đó.":
        "“Use these lyrics” puts the draft into the lyrics box (the old text can be restored). Nothing changes until then.",
    "Chưa có gì đổi cho tới khi bạn bấm “Dùng lời này”.": "Nothing changes until you press “Use these lyrics”.",
    "Máy sẽ nghe bài hát ngay trên máy này để đoán lời — không gửi bài đi đâu.": "This Mac will listen to the song locally to guess the lyrics — nothing is sent anywhere.",
    "Kết quả chỉ là BẢN NHÁP. Từ nào máy chưa chắc sẽ được đánh dấu để bạn xem lại; đoạn nhạc không lời sẽ để trống. Bạn xem xong và bấm “Dùng lời này” thì lời mới được đưa vào ô lời — sau đó việc canh giờ vẫn do bước “Tạo Karaoke” quen thuộc làm.":
        "The result is only a DRAFT. Words the app is unsure about are marked for you to review; instrumental parts stay empty. Lyrics only enter the lyrics box when you press “Use these lyrics” — timing is still done by the usual “Create Karaoke” step.",
    "Project chưa có file nhạc — hãy nhập nhạc trước.": "This project has no audio yet — import a song first.",
    "Project đang có lời trong ô lời — bản nháp sẽ hiện riêng bên cạnh để so sánh.": "This project already has lyrics — the draft will appear separately beside them for comparison.",
    "Có thể mất vài phút tuỳ máy.": "This may take a few minutes depending on your Mac.",
    "Cần phân tích nhạc trước": "Music analysis needed first",
    "Để biết đoạn nào có người hát (và để trống đoạn nhạc không lời), máy cần bản tách giọng hát của bài này. Bước “phân tích nhạc” của Tạo Karaoke tạo ra nó — bấm nút bên dưới để chạy đúng bước đó, rồi bấm “Bắt đầu”.":
        "To know where someone is singing (and leave instrumental parts empty), the app needs this song's separated vocal track. The “music analysis” step of Create Karaoke produces it — press the button below to run that same step, then press “Start”.",
    "Đang phân tích nhạc…": "Analyzing music…",
    "Đã có bản tách giọng hát.": "Vocal track is ready.",
    "Chưa lấy được lời": "Could not get the lyrics",
    "Project của bạn không bị thay đổi.": "Your project was not changed.",
    "Lời hiện tại (không đổi)": "Current lyrics (unchanged)",
    "Lời tự động (bản nháp)": "Generated lyrics (draft)",
    "%d từ": "%d words",
    "%d đoạn có giọng hát / %d đoạn": "%d of %d segments contain singing",
    "không có từ chưa chắc": "no uncertain words",
    "%d từ chưa chắc (cam, có dấu ?)": "%d uncertain words (orange, marked ?)",
    "%d đoạn ngân nga được để riêng": "%d humming segment(s) kept separate",
    "%d đoạn chưa xác nhận nên bỏ qua": "%d unconfirmed segment(s) skipped",
    "dòng %d": "line %d",
    "(có thể máy nghe thiếu từ này)": "(the app may have missed this word)",
    "Từ chưa chắc và phương án khác (%d)": "Uncertain words and alternatives (%d)",
    "Đang có một lượt lấy lời khác đang chạy.": "Another Auto Lyrics run is already in progress.",
    "máy chỉ nghe thấy từ này ở một bộ kiểm tra — có thể là từ bị thiếu": "only one of the checkers heard this word — it may be a missing word",
    "chưa có phương án khác": "no other options",
    "phương án khác:": "other options:",
    "Bấm vào từ màu cam để xem phương án khác.": "Click an orange word to see other options.",
    "Thử lại": "Try again",
    "Bộ nhận dạng đã dừng đột ngột (mã %d). Bấm “Thử lại”.": "The recognizer stopped unexpectedly (code %d). Press “Try again”.",

    // MARK: Hai đường tạo Karaoke (Có lời / Không cần lời)
    "Chọn cách tạo Karaoke": "Choose how to create Karaoke",
    "Tự động tạo Karaoke": "Auto Karaoke",
    "Bạn muốn tạo Karaoke theo cách nào?": "How do you want to create your Karaoke?",
    "Tôi có lời bài hát": "I have the lyrics",
    "Dán hoặc nhập lời — máy tự canh giờ.": "Paste or type the lyrics — the app times them for you.",
    "Không cần lời — Tự động tạo Karaoke": "Auto Karaoke — no lyrics needed",
    "Máy tự nghe, viết lời rồi canh giờ.": "The app listens, writes the lyrics and times them.",
    "Đổi cách tạo": "Change method",
    "Chưa có lời.": "No lyrics.",
    "Không cần nhập lời: máy nghe bài hát, viết ra lời, rồi tự canh giờ thành karaoke.": "No lyrics needed: the app listens to the song, writes the lyrics, then times them into karaoke.",
    "Bắt đầu tạo Karaoke": "Start creating Karaoke",
    "Chưa phân tích được bài hát": "Could not analyze the song",
    "Chưa nhận dạng được lời": "Could not recognize the lyrics",
    "Không thể tự canh thời gian": "Could not time the lyrics automatically",
    "Đang phân tích bài hát…": "Analyzing the song…",
    "Đang nhận dạng lời…": "Recognizing lyrics…",
    "Đang tự động canh thời gian…": "Timing the Karaoke automatically…",
    "Đã phân tích bài hát": "Song analyzed",
    "Đã nhận dạng lời": "Lyrics recognized",
    "Đã kiểm tra lời": "Lyrics checked",
    "Đã canh thời gian Karaoke": "Karaoke timed",
    "Hoàn tất — %d dòng đã có mốc giờ.": "Done — %d lines are timed.",
    "%d từ máy chưa chắc, xem ở tab “Sửa lời”.": "%d uncertain words — review them in the “Edit Lyrics” tab.",
    "Phân tích bài hát": "Analyze the song",
    "Nhận dạng lời": "Recognize lyrics",
    "Kiểm tra lời": "Check lyrics",
    "Tự động canh thời gian": "Time automatically",
    "Lời đã nhận dạng được giữ lại — không cần nhận dạng lại.": "The recognized lyrics are kept — no need to recognize again.",
    "Thử lại canh giờ": "Retry timing",
    "Ẩn lời đã nhận dạng": "Hide recognized lyrics",
    "Xem lời đã nhận dạng": "Show recognized lyrics",
    "Chuyển sang nhập lời thủ công": "Switch to typing lyrics manually",
    "Nhập lời thủ công": "Type lyrics manually",
    "Không phân tích được bài hát.": "The song could not be analyzed.",
    "Không nhận dạng được lời.": "The lyrics could not be recognized.",
    "Từ máy chưa chắc (%d)": "Uncertain words (%d)",
    "Karaoke đã canh giờ xong. Xem các từ dưới đây — chọn phương án đúng, hoặc bỏ qua nếu từ đang dùng đã đúng.": "Karaoke is timed. Check the words below — pick the right option, or keep the current word if it is correct.",
    "Giữ nguyên": "Keep as is",
    "(có thể thiếu từ)": "(a word may be missing)",
    "Dòng này có từ máy chưa chắc": "This line has words the app is unsure about",
]
